# Use postgres/example user/password credentials
version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pass123

    ports:
      - '5433:5432'
